import datetime
from unittest import TestCase

from pygramtic.models import Update, Message, Chat, InlineQuery, User, Location, \
    ChosenInlineResult, CallbackQuery, ShippingQuery, PreCheckoutQuery, Poll, \
    ShippingAddress, OrderInfo, PollOption, MessageEntity, Audio, Document, Animation, \
    Game, PhotoSize, Sticker, Voice, Video, VideoNote, Contact, Venue, Invoice, \
    SuccessfulPayment, InlineKeyboardMarkup, PassportData, MaskPosition, \
    EncryptedPassportElement, EncryptedCredentials, PassportFile, InlineKeyboardButton, \
    LoginUrl, CallbackGame


class TestModels(TestCase):
    def test_models(self):
        update = Update(
            update_id=1214234242342,
            message=Message(
                message_id=32525235234,
                date=datetime.datetime.now(),
                chat=Chat(
                    id=2435234523,
                    type='bot'
                ),
                forward_from=User(
                    id=352,
                    is_bot=True,
                    first_name='john',
                    last_name='wick',
                    username='johnwick',
                    language_code='en'
                ),
                forward_from_chat=Chat(
                    id=2435234523,
                    type='bot'
                ),
                forward_from_message_id=523232,
                forward_signature='afasf',
                forward_sender_name='afasf',
                forward_date=datetime.datetime.now(),
                reply_to_message=Message(
                    message_id=32525235234,
                    date=datetime.datetime.now(),
                    chat=Chat(
                        id=2435234523,
                        type='bot'
                    ),
                ),
                entities=[
                    MessageEntity(
                        user=User(
                            id=352,
                            is_bot=True,
                            first_name='john',
                            last_name='wick',
                            username='johnwick',
                            language_code='en'
                        )
                    )
                ],
                caption_entities=[
                    MessageEntity(
                        user=User(
                            id=352,
                            is_bot=True,
                            first_name='john',
                            last_name='wick',
                            username='johnwick',
                            language_code='en'
                        )
                    )
                ],
                audio=Audio(
                    thumb=PhotoSize()
                ),
                document=Document(
                    thumb=PhotoSize()
                ),
                animation=Animation(
                    thumb=PhotoSize()
                ),
                game=Game(
                    photo=[PhotoSize()],
                    text_entities=[
                        MessageEntity()
                    ],
                    animation=Animation(
                        thumb=PhotoSize()
                    ),
                ),
                photo=[PhotoSize()],
                sticker=Sticker(
                    mask_position=MaskPosition()
                ),
                video=Video(
                    thumb=PhotoSize()
                ),
                voice=Voice(),
                video_note=VideoNote(
                    thumb=PhotoSize()
                ),
                contact=Contact(),
                location=Location(),
                venue=Venue(
                    location=Location()
                ),
                poll=Poll(
                    options=[
                        PollOption(
                            text='aasf',
                            voter_count=34
                        )
                    ]
                ),
                new_chat_members=[
                    User(
                        id=352,
                        is_bot=True,
                        first_name='john',
                        last_name='wick',
                        username='johnwick',
                        language_code='en'
                    )
                ],
                left_chat_member=User(
                    id=352,
                    is_bot=True,
                    first_name='john',
                    last_name='wick',
                    username='johnwick',
                    language_code='en'),
                new_chat_photo=[PhotoSize()],
                pinned_message=Message(
                    message_id=32525235234,
                    date=datetime.datetime.now(),
                    chat=Chat(
                        id=2435234523,
                        type='bot'
                    ),
                ),
                invoice=Invoice(),
                successful_payment=SuccessfulPayment(
                    order_info=OrderInfo(
                        shipping_address=ShippingAddress()
                    )
                ),
                passport_data=PassportData(
                    data=[
                        EncryptedPassportElement(
                            files=[PassportFile()],
                            front_side=PassportFile(),
                            reverse_side=PassportFile(),
                            selfie=PassportFile()
                        )
                    ],
                    credentials=EncryptedCredentials()
                ),
                reply_markup=InlineKeyboardMarkup(
                    inline_keyboard=[[
                        InlineKeyboardButton(
                            text='adaaafa',
                            login_url=LoginUrl(),
                            callback_game=CallbackGame()
                        )
                    ]]
                ),
            ),
            editedMessage=Message(
                message_id=45234523,
                date=datetime.datetime.now(),
                chat=Chat(
                    id=3452345,
                    type='bot'
                )
            ),
            inline_query=InlineQuery(
                id='adadaa',
                from_user=User(
                    id=352,
                    is_bot=True,
                    first_name='john',
                    last_name='wick',
                    username='johnwick',
                    language_code='en'
                ),
                location=Location(
                    latitude=34,
                    longitude=34,
                )
            ),
            chosen_inline_result=ChosenInlineResult(),
            callback_query=CallbackQuery(
                id='adada',
                from_user=User(
                    id=352,
                    is_bot=True,
                    first_name='john',
                    last_name='wick',
                    username='johnwick',
                    language_code='en'
                ),
                message=Message(
                    message_id=45234523,
                    date=datetime.datetime.now(),
                    chat=Chat(
                        id=3452345,
                        type='bot'
                    )
                ),
                inline_message_id='3225'
            ),
            shipping_query=ShippingQuery(
                id='asdad',
                from_user=User(
                    id=352,
                    is_bot=True,
                    first_name='john',
                    last_name='wick',
                    username='johnwick',
                    language_code='en'
                ),
                invoice_payload='asdaf',
                shipping_address=ShippingAddress(
                    country_code='asd',
                    state='aasa',
                    city='ada',
                    street_line1='asdad',
                    street_line2='adasd',
                    post_code='asda',
                ),
            ),
            pre_checkout_query=PreCheckoutQuery(
                id='adaas',
                from_user=User(
                    id=352,
                    is_bot=True,
                    first_name='john',
                    last_name='wick',
                    username='johnwick',
                    language_code='en'
                ),
                currency='adasda',
                total_amount=344,
                invoice_payload='232as',
                shipping_option_id='dff4',
                order_info=OrderInfo(
                    name='afaf',
                    phone_number='asasf',
                    email='afafaf',
                    shipping_address=ShippingAddress(
                        country_code='asd',
                        state='aasa',
                        city='ada',
                        street_line1='asdad',
                        street_line2='adasd',
                        post_code='asda',
                    ),
                ),
            ),
            poll=Poll(
                id='adaaaaf',
                question='adaaa',
                options=[
                    PollOption(
                        text='aasf',
                        voter_count=34
                    )
                ],
                is_closed=False,
            )
        )
